### ISSUE TITLE
advantages of built in gridsearch vs sklearn

### ISSUE THREAD

**Issue by jwkvam** [dswah/pyGAM#100]
Could we use sklearn's grid search [functionality](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV) with pyGAM?

**Comment by dswah** [comment]
yes i think you probably can. 

I wanted an easier way of optimizing against different objectives (GCV/UBRE, AIC, AICc, ...) than having to write custom scorer callables.

**Comment by yiklun** [comment]
The built-in gridsearch function seems to be evaluating the objectives on the training data, rather than using cross-validation like the sklearn's GridSearchCV. Is that right? In that case the built-in gridsearch should be computationally more efficient?

**Comment by dswah** [comment]
Hmm that's a good point.

The built-in gridsearch uses generalized cross validation as it's objective, which is computationally more efficient than doing naive cross validation, as sklearn's GridSearchCV might impose on pyGAM.

aside from efficiency, i would love pyGAM to be compatible with sklearn functions like GridSearchCV or RandomizedSearchCV. :)

I believe one step required to do this is for each GAM to have a `.score()` method.
