### ISSUE TITLE
weights parameter?

### ISSUE THREAD

**Issue by gioelelm** [dswah/pyGAM#105]
Hi,

I would like to fit a model that in R (mgcv) would be:

```
gam(y~s(a, k)+s(b)+s(c), data=df, weights=vector_w)
```

this might translate to something like:
```
X = np.column_stack([a, b, c])
gam = LinearGAM(n_splines=[k, 25, 25])
gam.gridsearch(X, y)
XX = generate_X_grid(gam)
y_pred = gam.predict(XX)
```

Is there a way (even hacky) to use the prior weights on the contribution of samples on the log-likelihood?

Thanks

**Comment by dswah** [comment]
unfortunately there isnt an easy/hacky way to do that.

but adding that functionality to the package looks easy.
 im coming up with a PR today/tomorrow.

(this should also fix https://github.com/dswah/pyGAM/issues/98)

**Comment by dswah** [comment]
@gioelelm the PR is merged.
hope you can give it a try!
