### ISSUE TITLE
Support for link formulas like mgcv

### ISSUE THREAD

**Issue by more-data-please** [dswah/pyGAM#123]
Hello! Thanks for creating this library.  Is there support (or planned support) for specifying link formulas like the mgcv R package?  For example: log(y) ~ s(x1, x2, k=20)

**Comment by dswah** [comment]
Hey!

Ah, is this the patsy notation? http://patsy.readthedocs.io/en/latest/formulas.html

Adding this type of support is not high on my list of things to do (first want to add tensor splines, big data support, outer loop optimization, sampling...), but I would gladly help support it if people would find it useful.

Could you tell me why you like this notation?
-Dani

**Comment by more-data-please** [comment]
Thanks for the response, Dani.  I don't necessarily need that notation, but I wasn't seeing how to specify that kind of link function in PyGAM.  Is there a way to specify the equivalent in PyGAM? In mgcv the s() is used to specify the smooth terms and using the formula notation it gives the flexibility to specify formula like the above or like y ~ some_factor + s(x1) + s(x2).  If there's an existing way let me know, thanks!

**Comment by dswah** [comment]
Ah, i think see what you mean.

by default, pyGAM will fit univariate splines on each dimension of your X matrix,
so a simple way of doing `y ~ s(x1) + s(x2)` is to do `LinearGAM().fit(X)` where `X = np.hstack([x1, x2]) ` or similar.

you can get fancier and specify different numbers of splines per dimension of X by doing
`LinearGAM(n_splines=[20, 30]).fit(X)`

you can also choose the (non)linearity of the link function manually by doing `GAM(link='log').fit(X)` or similar

unfortunately, i think there is no simple way to add a known constant factor to the link function, ie `y ~ s(x1) + s(x2) + some_factor` ...

let me think about that...

**Comment by more-data-please** [comment]
Ok, that makes sense.  Any thoughts on non-linear interaction terms? In mgcv they are specified like s(x1, x2).  Can this be specified in PyGAM?

**Comment by dswah** [comment]
arg! not yet! i really want to add interaction terms. soon :)

**Comment by more-data-please** [comment]
thanks for answering all my questions, Dani!

**Comment by dswah** [comment]
my pleasure.
