### ISSUE TITLE
LogisticGAM not converging

### ISSUE THREAD

**Issue by jeweinberg** [dswah/pyGAM#125]
I keep getting the error below when trying to train a LogisticGAM. This error does not happen when I use sklearn LogisticRegression or RandomForest.

/opt/anaconda/envs/heartfailureNN/lib/python3.5/site-packages/pygam/links.py:149: RuntimeWarning: divide by zero encountered in true_divide
  return dist.levels/(mu*(dist.levels - mu))
/opt/anaconda/envs/heartfailureNN/lib/python3.5/site-packages/pygam/pygam.py:888: RuntimeWarning: invalid value encountered in multiply
  return sp.sparse.diags((self.link.gradient(mu, self.distribution)**2 * self.distribution.V(mu=mu))**-0.5)
/opt/anaconda/envs/heartfailureNN/lib/python3.5/site-packages/pygam/pygam.py:907: RuntimeWarning: invalid value encountered in greater_equal
  mask = (np.abs(weights) >= np.sqrt(EPS)) * (weights != np.nan)

**Comment by dswah** [comment]
I've seen the LogisticGAM fail to converge before, but I've never seen the following warnings:

`RuntimeWarning: invalid value encountered in greater_equal
mask = (np.abs(weights) >= np.sqrt(EPS)) * (weights != np.nan)`

nor 

`RuntimeWarning: invalid value encountered in multiply
return sp.sparse.diags((self.link.gradient(mu, self.distribution)2 * self.distribution.V(mu=mu))-0.5)`

Three things:
1. i need to release a new version of pyGAM that changes some of those lines (will do tonight). please try again after installing the new code.
2. could you attach your X and y data, and the command you ran?
3. Also, these are warnings. What error did you get?

**Comment by jeweinberg** [comment]
Here is the code below. The data itself is protect by federal statute, so I can't share that.


Traceback (most recent call last):
  File "secret", line 193, in <module>
    model.main()
  File "secret", line 187, in main
    gam_test = self.logit_gam(train_x, test_x, train_y)
  File "secret", line 149, in logit_gam
    gam.fit(train_x, train_y)
  File "/opt/anaconda/envs/heartfailureNN/lib/python3.5/site-packages/pygam/pygam.py", line 1133, in fit
    self._pirls(X, y)
  File "/opt/anaconda/envs/heartfailureNN/lib/python3.5/site-packages/pygam/pygam.py", line 998, in _pirls
    self._estimate_model_statistics(Y, modelmat, inner=None, BW=WB.T, B=B)
  File "/opt/anaconda/envs/heartfailureNN/lib/python3.5/site-packages/pygam/pygam.py", line 1206, in _estimate_model_statistics
    self.statistics_['edof'] = self._estimate_edof(BW=BW, B=B)
  File "/opt/anaconda/envs/heartfailureNN/lib/python3.5/site-packages/pygam/pygam.py", line 1247, in _estimate_edof
    np.random.shuffle(idxs)
  File "mtrand.pyx", line 4808, in mtrand.RandomState.shuffle (numpy/random/mtrand/mtrand.c:39350)
  File "mtrand.pyx", line 4811, in mtrand.RandomState.shuffle (numpy/random/mtrand/mtrand.c:39302)
TypeError: 'range' object does not support item assignment

**Comment by dswah** [comment]
Nice, thanks for posting.

That looks like an error from an old version of pyGAM, fixed a few releases ago...
(was doing `np.random.shuffle(range(...))` but needed to do `np.random.shuffle(list(range(...)))` for py3)

Could you verify that you have the newest version installed?

**Comment by jeweinberg** [comment]
I just installed from pip the other day. I'll install from your repo this
morning and see what happens. Can you push the new version to pip?

**Comment by dswah** [comment]
@jeweinberg i published the new version. can you install again?
you shouldn't be seeing that `TypeError`.

**Comment by jeweinberg** [comment]
I was able to use the model today without error. Thanks! I think this issue is resolved.

**Comment by dswah** [comment]
kewl :)

**Comment by michaeljfazio** [comment]
Is it possible that there was a regression on this issue. I'm using the latest version installed with pip 0.8.0 and I get the exact same issue quite often:

```
100% (11 of 11) |########################| Elapsed Time: 0:00:00 Time:  0:00:00
N/A% (0 of 11) |                         | Elapsed Time: 0:00:00 ETA:  --:--:--/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pygam/links.py:149: RuntimeWarning: divide by zero encountered in true_divide
  return dist.levels/(mu*(dist.levels - mu))
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pygam/pygam.py:592: RuntimeWarning: invalid value encountered in multiply
  self.distribution.V(mu=mu) *
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pygam/pygam.py:614: RuntimeWarning: invalid value encountered in greater_equal
  mask = (np.abs(weights) >= np.sqrt(EPS)) * np.isfinite(weights)
```
