### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by BeckHamed** [dswah/pyGAM#127]
To create a GAM model require a formula (with eventually some spline function). 
Where can one defines the formula ? Most functions have x and y as input. assuming that the y is target variable and x list of features, where the data should be introduced? and more important where the formula should be introduced?

**Comment by dswah** [comment]
Hi @BeckHamed,

This GAM tool assumes (for now) your function is additive in your spline functions. 

So for all of the models we have
`g(y) = s(x1) + s(x2) + ... + s(xn) + c`

where `g` is your link function. 

You can use the pre-built GAM classes (like LinearGAM, LogisticGAM, ...) or specify your own GAM, link function and distribution. 

You can specify the number of splines and sie order per feature if you wish via:
`gam = GAM(n_splines=[5, 10], spline_order=[0, 3], distribution="normal", link="identity")`

then to fit your model you do:

`gam.fit(X, y)`
