### ISSUE TITLE
gam.coef_ shape not matching documentation description

### ISSUE THREAD

**Issue by zmcode** [dswah/pyGAM#128]
Hi @dswah,
thank you for this great package! 
According to the documentation, the `gam.coef_` matrix should have a shape that is `(n_samples, m_features)`. However, in my case the `gam.coef_` is a 1-d array with a completely different size.

Am I missing something or is there an error somewhere?

**Comment by dswah** [comment]
hey @zmcode,
oh wow that does seem wrong! thanks for pointing that out.

the shape of the `gam. coef_` should be a vector of length:

`(intercept==True) + n_splines_feature_1 + n_splines_feature_2 + ...+ n_splines_feature_n`

does that match what you're seeing?
-dani

**Comment by zmcode** [comment]
I am using a `LinearGAM()` with default parameters, so `n_splines` should be 25. 
Each entry in my dataset has 6 features and `intercept` is set to `True`.
So if I am understanding your definition correctly, the length of `gam.coef_` should be 151 but `len(gam.coef_)` outputs 132.

**Comment by dswah** [comment]
ok cool. this is good information. 

pyGAM also tries to automatically infer if you have any categorical feature(s) and will use one indicator feature for each category. 

could you check `gam.dtypes_` for your fitted model? it should return a list with the inferred data type for each feature.

**Comment by zmcode** [comment]
Yep I have two categorical features, the content of `gam._dtype` is 
```
['categorical',
 'categorical',
 'numerical',
 'numerical',
 'numerical',
 'numerical']
```

**Comment by dswah** [comment]
alright. that makes some sense. 

i forgot that you can check the number of splines per feature by inspecting `gam._n_splines`. this should help you decide if the number of categories is appropriate for your data. 

if instead you want to force pyGAM to use numerical features, you can start your `LinearGAM` with `dtype="numerical"` to set all features at once, or specify a list with entries per feature like `dtype=["numerical", "categorical", ...]`

**Comment by zmcode** [comment]
I have checked the `gam._n_splines` attribute and it confirms the output of `len(gam.coef_)` as well as being appropriate for my data. Thank you for your help :)

**Comment by dswah** [comment]
cool :)
