### ISSUE TITLE
Density-dependent confidence intervals?

### ISSUE THREAD

**Issue by naught101** [dswah/pyGAM#132]
Is it possible to get density-dependent or input-dependent confidence intervals?

For example:

```python
import numpy as np
from matplotlib import pyplot as plt
from pygam import LinearGAM

gam = LinearGAM()

x = np.random.random(1000)*10
y = 5/(x+1) * np.random.randn(1000)

gam.fit(x, y)

plt.scatter(x, y)

x_pred = np.linspace(min(x), max(x), num=100)
y_pred = gam.predict(x_pred)
y_int = gam.prediction_intervals(x_pred, width=.95)

ax = plt.gca()
ax.plot(x_pred, y_pred, 'r-')
ax.fill_between(x_pred, y_int[:, 0], y_int[:, 1], alpha=0.1, facecolor='r')
```

Produces this: 

![gam test](https://user-images.githubusercontent.com/167164/33690359-4303cb60-db37-11e7-95a1-4757d50011c2.png)
 
But these confidence intervals don't seem all that useful. Is there a way to get confidence intervals that change dependent on the local conditions?

**Comment by dswah** [comment]
ah, right..

I think the biggest problem is that GAMs estimate `E[y] = f(x_1) + f(x_2) + ... + e`
where `e ~ N(0, sigma**2)`
so there is one sigma for the whole GAM. 

The only model parameter that is a conditional on X is the mean. the variance is the same for the whole model.

I think GAM-LSS (generalized additive models for location scale and shape) do what you're thinking.
here the location (mean), scale (variance) and shape (3rd + 4th moments) are all conditional on X.
(http://www.gamlss.org/)

**Comment by dswah** [comment]
@naught101 

i know that the prediction interval is a combination of confidence interval of the local mean plus the estimated variance of the whole model. 

so for locations where there is more uncertainty in the mean, i would expect that the confidence interval would be wider, and therefore the prediction interval would depend on the location too.

not quite seeing this effect with the model right now...

adding just a couple of lines of code to youre snippet:

here is the confidence interval of the estimated mean
```
pdep, confi = gam.partial_dependence(x_pred, feature=1, width=.95)
plt.plot(confi[0])
```
![image](https://user-images.githubusercontent.com/11619412/33692095-7a2a8346-daa0-11e7-872b-6228d4c77e4e.png)

now lets check how the width of the mean changes for a given X
```
plt.plot(confi[0][:,1] - confi[0][:,0])
```
![image](https://user-images.githubusercontent.com/11619412/33692120-9a5aac54-daa0-11e7-866a-d45bf9110dec.png)

not much variation except at the ends where we dont know what happens.

**Comment by naught101** [comment]
right, but that is because in my example, X is basically uniform, right? If I do `x = (np.random.random(1000)*2) ** 4` (to get a bit of non-uniformity), then your first plot looks like:

![figure_1](https://user-images.githubusercontent.com/167164/34923689-3813de28-f9f2-11e7-97af-fb9284d23536.png)

Most of the data that I would be looking at would be at least as non-uniformly distributed as that, and usually also contains clusters..

Would it make sense for pyGAM to include GAM-LSS? The link is now down, unfortunately, but the original paper is at http://onlinelibrary.wiley.com/doi/10.1111/j.1467-9876.2005.00510.x/full , and there is an updated, publicly accessible paper at https://www.jstatsoft.org/article/view/v023i07. I haven't read either yet.

**Comment by dswah** [comment]
@naught101 oh ok. i believe i have misunderstood your question.
your question was about confidence intervals, but your first plot showed prediction intervals, which confused me.

i found the fossil/strontium data and produced plots for both confidence and prediction intervals.

here is the code
```
fossil = pd.read_csv('fossil.csv').values
ymin = fossil[:,1].min()*.99999
ymax = fossil[:,1].max()*1.00001

X = fossil[:,0]
y = fossil[:,1]

gam = LinearGAM().gridsearch(X, y)
XX = generate_X_grid(gam)


### Confidence Intervals ###
plt.scatter(fossil[:,0], fossil[:,1], color='k', s=5)

plt.plot(XX, gam.predict(XX), color='k')

confi = gam.confidence_intervals(XX)
plt.fill_between(XX.ravel(), y1=confi[:,0], y2=confi[:,1], color='k', alpha=0.2)

plt.ylim(ymin, ymax)


### Prediction Intervals ###
plt.scatter(fossil[:,0], fossil[:,1], color='k', s=5)

plt.plot(XX, gam.predict(XX), color='k')

confi = gam.prediction_intervals(XX)
plt.fill_between(XX.ravel(), y1=confi[:,0], y2=confi[:,1], color='k', alpha=0.2)

plt.ylim(ymin, ymax)
```

and the plots:
![image](https://user-images.githubusercontent.com/11619412/35069555-5a22b7ac-fb8f-11e7-8f84-6f1b048fd15d.png)
![image](https://user-images.githubusercontent.com/11619412/35069560-6014612e-fb8f-11e7-9dce-25c79030f357.png)

indeed, the width of the confidence intervals depends on the density of the samples. the width of the prediction intervals is also determined by the variance of the error distribution, which is is assumed equal across the whole model. (however there is also a bug that makes these typically too wide).

**Comment by dswah** [comment]
fossil/strontium data for reference
[fossil.csv.zip](https://github.com/dswah/pyGAM/files/1640829/fossil.csv.zip)

**Comment by naught101** [comment]
Ah.. I hadn't realised there was a difference. My plots look a LOT more sensible now. Thanks! I guess this can be closed?
