### ISSUE TITLE
Recurring error in links.py due to Numpy

### ISSUE THREAD

**Issue by AnastasiaVarlet** [dswah/pyGAM#133]
Hi!

I observe a recurring error message when using GammaGAM and InvGaussianGAM: "ValueError: Integers to negative integer powers are not allowed".

This seems to be generated by for example the row 304 in links.py, where the power is applied as follows: "mu**-2" (but such powers occurs more than once in this script).

It seems that Numpy doesn't allow this but would allow "mu**-2.0". See here for more info: https://stackoverflow.com/questions/43287311/why-cant-i-raise-to-a-negative-power-in-numpy

Would be nice if you could implement this quick fix, adding a ".0" :) Thanks!

**Comment by dswah** [comment]
@AnastasiaVarlet 
great find! i will take a look

**Comment by dswah** [comment]
ive replicated this error. here is the change you suggested (in a few places)

https://github.com/dswah/pyGAM/pull/134
