### ISSUE TITLE
How to get rid of the progress bar in pyGAM program?

### ISSUE THREAD

**Issue by sunshine1204** [dswah/pyGAM#140]
Very good and effective library!  
I wanted to embed 'pyGAM' into my own python program, but it would have a progress bar in each loop, so that it would take a long time to run. If I can remove it and not let it run, the program will run very fast. (The screenshot of issue is below.)
So, how can I get rid of progress bar in your pyGAM program without changing other functions ? 
Coul you help me? Thanks in advance!

![issue](https://user-images.githubusercontent.com/18735308/34613918-95996520-f26a-11e7-8cfa-58ed112a4940.png)

**Comment by sunshine1204** [comment]
Hi, daniel.
I try to modify your codes with the following changes and it seems to work. 
![issure](https://user-images.githubusercontent.com/18735308/34758555-f3e2af6a-f611-11e7-8881-78200675b0c9.png)

Meanwhile, Some reminders appears. Can I ignore these ?

![issure 2png](https://user-images.githubusercontent.com/18735308/34758619-68b78086-f612-11e7-9d71-0c27251ffc26.png)

**Comment by dswah** [comment]
@sunshine1204 perfect that should do the trick

those warnings are telling you that your search space has some invalid members. 
the code will skip any invalid configuration like those where `n_splines` is too low.

**Comment by dswah** [comment]
ideally we would have a `verbose=False` keyword argument that turns off the progressbar and silences the warnings.

**Comment by sunshine1204** [comment]
Thank you very much, daniel! @dswah 
Looking forward to your improvement.

**Comment by dswah** [comment]
new functionality added!
thanks @sunshine1204

**Comment by dswah** [comment]
you just have to run `gam.gridsearch(..., progress=False)`

**Comment by sunshine1204** [comment]
Thank you very much!

**Comment by dswah** [comment]
@sunshine1204 i still need to publish this update to pypi, but please check for a new version tomorrow :)

**Comment by sunshine1204** [comment]
Ok, I will. Good luck.
