### ISSUE TITLE
Converter works for IList<T> but not for T[] (array)

### ISSUE THREAD

**Issue by jjaskulowski** [dswah/pyGAM#147]
I lost hours on this. 
converter.ToPython does not enter condition "if (value is IList && value.GetType().IsGenericType)" for arrays.

Why is this Generic condition even needed? It should work fine for any object.

As addition, this condition should also work for any ICollection.

Otherwise, great job!

**Comment by dswah** [comment]
@jjaskulowski im not sure what this is about. perhaps you meant the repo pygame?

**Comment by jjaskulowski** [comment]
@dswah. Whoops, sorry, I meant pythonnet/pythonnet :)
