### ISSUE TITLE
Gridsearch with only a single LAM parameter

### ISSUE THREAD

**Issue by karischoonbee** [dswah/pyGAM#170]
We're using pyGAM as a way to extract an array of features (the GAM coefficients) to characterise a distribution. We noticed that the first of the default LAM parameters is almost always chosen. It would speed up the feature extraction significantly if we could constrain the gridsearch to a single LAM parameter (currently the length of the vector has to be > 1).

**Comment by dswah** [comment]
Hey @karischoonbee 

Cool, I think I understand. 

If you know what your smoothing parameter should be a-priori, then you can fit your GAM without gridsearch at all by doing:

```python
gam = GAM(..., lam=0.001).fit(X, y)
```

The gridsearch method is useful for when you dont know the appropriate amount of smoothing a-priori and you want to estimate this as well.

Please let me know if this works for you,
Dani

**Comment by karischoonbee** [comment]
Yes, that's exactly what I want to do but I'm getting

> ValueError: lam grid must either be iterable of iterables, or an iterable of length > 1, but found 0.001

using LinearGAM()

**Comment by karischoonbee** [comment]
I was indeed calling `gridsearch()` directly, apologies! I'll pass it to the constructor instead.

**Comment by dswah** [comment]
cool!
