### ISSUE TITLE
how do i install pygam

### ISSUE THREAD

**Issue by mchari** [dswah/pyGAM#172]
I tried pip install pygam and got the following errors : 
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

pip install pygam
Collecting pygam
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connec
tion broken by 'ProtocolError('Connection aborted.', error(10054, 'An existing c
onnection was forcibly closed by the remote host'))': /simple/pygam/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connec
tion broken by 'ProtocolError('Connection aborted.', error(10054, 'An existing c
onnection was forcibly closed by the remote host'))': /simple/pygam/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connec
tion broken by 'ProtocolError('Connection aborted.', error(10054, 'An existing c
onnection was forcibly closed by the remote host'))': /simple/pygam/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connec
tion broken by 'ProtocolError('Connection aborted.', error(10054, 'An existing c
onnection was forcibly closed by the remote host'))': /simple/pygam/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connec
tion broken by 'ProtocolError('Connection aborted.', error(10054, 'An existing c
onnection was forcibly closed by the remote host'))': /simple/pygam/
  Could not find a version that satisfies the requirement pygam (from versions:
)
No matching distribution found for pygam

**Comment by dswah** [comment]
@mchari hmm that looks annoying..

im currently without a real computer (im travelling through a bunch of national parks :) so i cannt dig very deep right now. 

have you looked at this [error and solution?](https://stackoverflow.com/questions/33996026/pip-not-installing-modules?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

it looks very similar to yours.

i hope to get a better chance to looks at this in a week or two. 
sorry about that.

**Comment by mchari** [comment]
Thanks. Using --proxy worked.

**Comment by dswah** [comment]
@mchari great!
