### ISSUE TITLE
Installation Directions

### ISSUE THREAD

**Issue by adumudaliar** [dswah/pyGAM#18]
Hello,
           I was hoping to try out your implementation of GAM. However I am not sure how I can do that.
Thanks,
Vinod

**Comment by dswah** [comment]
😄 

Hey Vinod,
The package is very raw right now, and only Logistic GAMs have been implemented.

I am still squashing basic bugs and adding essential functionality.
I would hate to waste your time with a premature implementation. 😉 

Please check-back in a few days,
-Dani

**Comment by dswah** [comment]
but yes, i also need to add installation instructions

**Comment by dswah** [comment]
note to self, use flit: https://github.com/takluyver/flit

**Comment by dswah** [comment]
@adumudaliar ready to install :)
