### ISSUE TITLE
Is it possible to return the feature functions?

### ISSUE THREAD

**Issue by edwardcjohnson** [dswah/pyGAM#193]
Thanks for developing a great tool!
I would like to be able to return the feature functions f_i() that are built using penalized B splines.
Is this possible?
I appreciate your help.

**Comment by dswah** [comment]
@edwardcjohnson hey there!
i think the gam  [`partial_dependence`](https://github.com/dswah/pyGAM/blob/master/pygam/pygam.py#L1807) method might be what you're looking for. 

with this method you can evaluate the feature functions on new data points. 
if you call the method with `X=None` it will return the values of the feature function over an evenly sampled grid of points for nice plotting. (you can see some examples in the readme)

please let mw know if this works for you...
-dani

**Comment by edwardcjohnson** [comment]
Hi @dswah ,
What I'm looking for is a method that would allow me to return the feature functions themselves (or perhaps a list of tuples where each element of the tuple represents some component of the feature function)?
What i'm interested in is seeing the 'nuts and bolts' of the feature functions so i'd like to see their construction.
Does that make sense?

Thanks!
-Edward

**Comment by dswah** [comment]
does that help?

**Comment by edwardcjohnson** [comment]
This is exactly what I was looking for! Thank you very much for your help.
