### ISSUE TITLE
categorical variable and linear terms?

### ISSUE THREAD

**Issue by BrianMiner** [dswah/pyGAM#197]
Hello!

Is there a way at present to including categoriical terms (dummy coding) or otherwise include a linear weight on the feature without a spline?

**Comment by dswah** [comment]
@BrianMiner yes, you can do both of those things. 

you just have to line up the feature vector with the GAM constructor arguments. 

for example, lets assume that in the feature vector we want a spline first feature, a categorical second feature, and a linear third feature. then we would build:

`LinearGAM(fit_splines=[True, True, False], fit_linear=[False, False, True], dtype=['numerical', 'categorical', 'numerical'])`

the reason that the fit_splines is true for the categorical feature is that in pygam categorical functions are built from 0th degree splines. 

the present construction is quite verbose, and this is going to change in the coming days. 

let me know if this helps!

**Comment by dswah** [comment]
i forgot to mention that the data for the categorical feature should already be transformed to integers. 

if you have N categories, then the categorical data must be integers from 0 to N-1.

**Comment by BrianMiner** [comment]
Thank you! Will a one hot encoding be done to the categorical feature (and will it drop a level)?

On 09/03/2018 12:15 PM, daniel servén wrote:

i forgot to mention that the data for the categorical feature should already be transformed to integers.

if you have N categories, then the categorical data must be integers from 0 to N-1.

**Comment by AllardJM** [comment]
So....if you already do a one-hot (N-1) in order to allow the intercept, should you do this for each dummy - else a dummy coded variable will be expanded to 2 variables if you list it as categorical?

fit_splines=[False], fit_linear=[True], dtype=['numerical']

**Comment by dswah** [comment]
@AllardJM

yes! thats a good idea!
