### ISSUE TITLE
Does pygam generate a model matrix?

### ISSUE THREAD

**Issue by daventero** [dswah/pyGAM#198]
I have used mgcv's R package for gam modelling. MGCV allows you to access model matrices by using [function model.matrix](https://www.rdocumentation.org/packages/mgcv/versions/1.8-24/topics/model.matrix.gam
).

Is there any equivalent way to obtain pygam's model matrix?

**Comment by dswah** [comment]
@daventero yes it does:
you can do 
```python
gam._modelmat(X)
```
which returns a sparse model matrix.

(you can use `gam._modelmat(X).A` to cast it to dense a numpy array.)

**Comment by dswah** [comment]
@daventero let me know if this is sufficient for you, and if we should close the issue.

**Comment by dswah** [comment]
@daventero im going to close this issue.

please simply re-open it if anything needs more explanation.

**Comment by daventero** [comment]
Yes @dswah that would answer my question, I'm sorry for the delayed response. Thanks!

**Comment by dswah** [comment]
with the model matrix you can reconstruct the p-splines:

some imports
```python
from pygam import *
from pygam.datasets import wage

from matplotlib import pyplot as plt
```

fit the model
```python
X, y = wage()
gam = LinearGAM(s(0) + s(1) + f(2)).fit(X, y)
```
now plot
```python
for i, term in enumerate(gam.terms):
    if term.isintercept:
        continue
    
    XX = gam.generate_X_grid(term=i)
    splines = gam._modelmat(XX, term=i).A
    
    plt.figure()
    fig, axs = plt.subplots(2, 1)
    
    # plot unweighted p-splines
    axs[0].plot(splines)
    axs[0].set_title(repr(term))
    
    # plot weighted p-splines
    idxs = gam.terms.get_coef_indices(i)
    axs[1].plot(splines * gam.coef_[idxs])
    
    plt.show()
```
![image](https://user-images.githubusercontent.com/11619412/45493790-d81f8f80-b76f-11e8-9434-460b6eda4cf9.png)
![image](https://user-images.githubusercontent.com/11619412/45493803-dfdf3400-b76f-11e8-9a1a-51c6623948e4.png)
![image](https://user-images.githubusercontent.com/11619412/45493809-e4a3e800-b76f-11e8-9601-ff4bc72449d5.png)
