### ISSUE TITLE
gridsearch fails with grid of n_splines

### ISSUE THREAD

**Issue by ric70x7** [dswah/pyGAM#205]
Hi, 
I found an error that was not occurring in a previous version (before .5 I think). I'm currently using version 0.7.0

Here is some data:
n_data = 40
X = np.random.uniform(0, 3 * np.pi, n_data)
Y = np.sin(X) + np.random.normal(0, .4, n_data)

This works fine:
m.gridsearch(X[:, None], Y, lam=np.arange(5, 31, 5))

However, if I call
m.gridsearch(X[:, None], Y, lam=np.arange(5, 31, 5), n_splines=np.arange(5, 31, 5)) 

then I can no longer use object m. For example, with
m.summary() 

I get the error AttributeError: GAM has not been fitted. Call fit first.

Cheers,
Ricardo

**Comment by dswah** [comment]
thanks for reporting that bug, 

it looks like it could be a type-ing problem since if i use python's standard `range` then it works:

```
m.gridsearch(X[:, None], Y, lam=np.arange(5, 31, 5), n_splines=range(5, 31, 5))
```

**Comment by dswah** [comment]
@ric70x7 thanks again for finding this bug, i pushed a new version 0.7.1. 

please let me know if this is working for you.

**Comment by kwangjae5033** [comment]
Hi, @dswah, 

I got the same error "AttributeError: GAM has not been fitted. Call fit first." 
when I give iterations less than 8 on "n_splines" argument for LinearGAM gridsearch. 

The number of iterations do not matter on "lam" argument
