### ISSUE TITLE
gam.summary() - return String rather than "printing" to standard out

### ISSUE THREAD

**Issue by marknormanread** [dswah/pyGAM#210]
Or add another method that returns as String to retain backwards compatibility. 

This would enable easier saving of statistics to the file system, which can be more useful if incorporating pyGAM into a pipeline. 

Currently I'm having to redirect stdout, which works, but it's a bit inelegant. 

Thanks!

**Comment by dswah** [comment]
@marknormanread thats interesting!

most of the statistics printed by the `summary()` method are stored in `gam.statistics_` although they might require a little post-processing 

which statistics are you interested in!

-dani

**Comment by dswah** [comment]
@marknormanread i am going to close this issue with your permission.
please re-open it if you see fit!
