### ISSUE TITLE
ImportError: cannot import name 'generate_X_grid'

### ISSUE THREAD

**Issue by tiago-monge** [dswah/pyGAM#214]
I successfuly installed the pygam package, but when I do

`from pygam.utils import generate_X_grid`

It gives this error:

 ```
Traceback (most recent call last):

  File "<ipython-input-23-58b7fe4be83a>", line 1, in <module>
    from pygam.utils import generate_X_grid

ImportError: cannot import name 'generate_X_grid'
```

What am doing wrong, or is it a bug? How to solve it?

Thanks

Tiago

**Comment by dswah** [comment]
@tiago-monge 

`generate_X_grid` was moved.
it is now a method of any GAM object, so you can do 

```python
gam = GAM().fit(X, y)
gam.generate_X_grid(term=...)
```


it looks like you are referencing some out-of-date usage.
where did you read that?

sorry for the confusion,
Dani

**Comment by dswah** [comment]
ahh is that from the CodeBurst tutorial?

**Comment by tiago-monge** [comment]
Thanks for the prompt answer. Yes, I was following the CodeBurst tutorial. I'll try with the new approach.

**Comment by dswah** [comment]
cool,
ok we will have to update/change that tutorial.
