### ISSUE TITLE
a bug in terms.py?

### ISSUE THREAD

**Issue by jzang18** [dswah/pyGAM#218]
keep getting error msg:
pygam/terms.py:244: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  return (np.atleast_1d(self.constraints) != None).any()

It works fine after I changed it to:
  return np.atleast_1d(self.constraints) is not None

any comments?

**Comment by jzang18** [comment]
I use python 2.7.15 and numpy 1.11.3

Seems this Numpy version not broadcast '!='.  I  think change to the following should work:
return np.not_equal(np.atleast_1d(self.constraints), None).any()

**Comment by dswah** [comment]
@jzang18 my mistake. this bug was just fixed in a previous PR https://github.com/dswah/pyGAM/pull/217, but i have not yet published the new version.

i will close this issue.

**Comment by jzang18** [comment]
thanks!
