### ISSUE TITLE
LinearGAM() vs. GAM()?

### ISSUE THREAD

**Issue by moptis** [dswah/pyGAM#233]
Perhaps not the best place for this question, but I was curious what the difference is. Are both suitable for regression?

**Comment by arose13** [comment]
`GAM()` is general and can be used for anything, It defaults to `distribution='normal', link='identity'` which makes it identical to `LinearGAM()`. In fact LinearGAM etc all inherits the `GAM()` class. 

Check out the documentation for more information birb [docs](https://pygam.readthedocs.io/en/latest/api/gam.html#pygam.pygam.GAM)

**Comment by dswah** [comment]
@moptis sorry for the poor response time. @arose13 is absolutely right; the GAM() class is the general class from which LinearGAM and the rest inherit. 

This means that GAM typically lacks some convenient functionality specific to the other models and distributions. For example LinearGAM has a prediction intervals method which the rest do not currently have.
