### ISSUE TITLE
Constraint to obtain non-negative predict( ) output?

### ISSUE THREAD

**Issue by L4student** [dswah/pyGAM#234]
I recently started using pygam and based on the docs there does not seem to be an explicit constraint I can use to constrain output from the `gam.predict` as positive. Would you know of any alternate approach I could take to constrain my output to only positive values? Thanks.

**Comment by dswah** [comment]
Hey @L4student!
Yes, the way to do this is to choose a distribution that only produces positive values like Gamma or Poisson. 

I would suggest you try the GammaGAM or PoissonGAM, depending on if you're modeling continuous or discrete values.

**Comment by dswah** [comment]
Hey @L4student!
Yes, the way to do this is to choose a distribution that only produces positive values like Gamma or Poisson. 

I would suggest you try the GammaGAM or PoissonGAM, depending on if you're modeling continuous or discrete values.

**Comment by L4student** [comment]
Thanks for the answer, @dswah .
