### ISSUE TITLE
Can I develop a GAMM(Generalized Additive Mixed  Models) in this package?

### ISSUE THREAD

**Issue by chjq201410695** [dswah/pyGAM#243]

**Comment by dswah** [comment]
@chjq201410695 unfortunately no. The estimation of GAMM is quite different.

However, you might consider a non-parametric model of your data's distribution using [expectiles](https://pygam.readthedocs.io/en/latest/notebooks/tour_of_pygam.html#Expectiles). Expectiles and quantiles are [very closely related](https://freakonometrics.hypotheses.org/files/2017/05/erasmus-1.pdf), while expectiles are much easier to fit.

You can achieve this using `ExpectileGAM` and even search for a particular quantile using `gam.fit_quantile(X, y)`

**Comment by dswah** [comment]
@chjq201410695 Unfortunately no. pyGAM cannot estimate GAMMs currently.

**Comment by chjq201410695** [comment]
> @chjq201410695 Unfortunately no. pyGAM cannot estimate GAMMs currently.

OK, thanks for your response; do you have plan to involve GAMMs in near future?

**Comment by dswah** [comment]
> OK, thanks for your response; do you have plan to involve GAMMs in near future?

no, not in the near future :/
There are other more urgent things that i would like to fix before adding new features.

**Comment by chjq201410695** [comment]
> > OK, thanks for your response; do you have plan to involve GAMMs in near future?
> 
> no, not in the near future :/
> There are other more urgent things that i would like to fix before adding new features.

OK, good luck!  I will close this issue.
