### ISSUE TITLE
Question about penalty terms

### ISSUE THREAD

**Issue by kaibenning** [dswah/pyGAM#272]
Thank you for this awesome library!

If I set constraints e.g. monotonic decreasing to a term s() of the Linear-GAM, is the penalty on the second-order-derivate still applied? Will I have a <img src="https://render.githubusercontent.com/render/math?math=\lambda_1"> for the monotonic constraint and a <img src="https://render.githubusercontent.com/render/math?math=\lambda_2"> for the second-order-derivative penalty or just one?

The `gam.summary()` method gives me just [<img src="https://render.githubusercontent.com/render/math?math=\lambda_1">]. Is this the expected behaviour? And if i want to can I do both?

**Comment by shyamcody** [comment]
You can provide as many lambdas as many penalties you provide. There is a check in the generic `Term` class to check that if lambda is iterable and penalties parameter is iterable, then whether they are the same or not. If not the same, it raises a valueError.  Also, for constraints, internally a strong lam is provided(`1e9`). You can't access this parameter from the user end, neither gam.summary() will output this value.

**Comment by kaibenning** [comment]
Thank you! : )
