### ISSUE TITLE
pyGAM support python 3.8?

### ISSUE THREAD

**Issue by LishengSun** [dswah/pyGAM#312]
Dear pyGAM authors,

Thank you for the great library. 
I found in the current documentation that it requires python >=3.6 (https://pypi.org/project/pygam/). Do you think python 3.8 will be supported as well?

Thank you in advance.

**Comment by dswah** [comment]
sorry for never responding!
i hope you tried it out for yourself!
currently pygam supports python 3.8 - 3.12
