### ISSUE TITLE
Version number hard coded

### ISSUE THREAD

**Issue by MMCMA** [dswah/pyGAM#336]
If I am not mistaken - the version number in [__init__](https://github.com/dswah/pyGAM/blob/master/pygam/__init__.py) is hard coded - and currentl set to the wrong version. I can recommend adding [versioneer](https://github.com/python-versioneer/python-versioneer/blob/master/INSTALL.md) which should take care of this automatically.

**Comment by dswah** [comment]
thank you for pointing this out! 
this is very confusing.

i am fixing with poetry-dynamic versioning, which uses git tags to figure out the version
