### ISSUE TITLE
Contribution of each smooth term

### ISSUE THREAD

**Issue by AdamWhiteXAI** [dswah/pyGAM#358]
Is there anyway I can get the 'additional contribution' each smooth term makes to the final GAM score for a particular input? For example if my model is :
LinearGAM( terms=s(7) + s(13) + s(1) + s(15)  + intercept) 
then what contribution does s(7) make when 'variable 7' equals 10

Is it worth trying to hack into PyGam's code to get this?

**Comment by CodeCrux21** [comment]
what do you mean? it's the coefficient. it's an additive model.

**Comment by AdamWhiteXAI** [comment]
There isn't a single coefficient for a dependent variable in a GAM, it's value varies based on the value of the dependent variable.

**Comment by AdamWhiteXAI** [comment]
But the point is that for a particular observation, you cannot get the single coefficient value that is being applied for to a specified dependent variable. You can in R but not in PyGAM

**Comment by ouslan** [comment]
@AdamWhiteXAI  What exactly is it that you want to implement? I imagine you are using the mgcv package from R. Could you link the documentation from R for the desired feature?

**Comment by AdamWhiteXAI** [comment]
Using MGCV, I am adding ‘type= terms’ to predict to give the contribution that each term makes to the total prediction:
predict(model, newdata = data, type = "terms")

I discovered this functionality from Chat GPT and can confirm that it returns a value for each dependent variable that sums to the prediction. However there appears little documentation on this in  “Package ‘mgcv’ December 21, 2023”.
