### ISSUE TITLE
Poisson model does not accept weights or interval of time

### ISSUE THREAD

**Issue by plafl** [dswah/pyGAM#98]
When using Poisson models the data to be fitted is the number of events per unit of time, but the interval of time can be variable for each sample. There are some possible solutions for this:

1. Add a `time` parameter to the fit/predict method
2. Add a `time` feature to the data that will be used by fit/predict
3. Divide the observed number of events by interval of time and weight each sample with the interval of time

However, from what I saw in the source code none of this solutions is available right now.

**Comment by dswah** [comment]
thanks for this important piece of feedback. i ignored exposure when making the api. 

luckily, a fix might not be too hard.

**Comment by brianholland** [comment]
I'll second this one - offsets would generally be useful.  Is it being addressed soon by any chance?  By the way I was delighted to see you'd made this repo!

**Comment by dswah** [comment]
@brianholland @plafl The PR with Poisson exposures and weights is merged!
plz give it a try if you get the chance :)
